USE techvelvet;

DROP TABLE IF EXISTS `USER_ROLE`;

CREATE TABLE USER_ROLE (
   USER_ID INT,
   ROLE_ID INT,
   PRIMARY KEY (USER_ID, ROLE_ID)
);

ALTER TABLE USER_ROLE ADD CONSTRAINT usersREFrole
   FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);

ALTER TABLE USER_ROLE ADD CONSTRAINT usersREFrole2
   FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID);

INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES
    (1, 1),
    (1, 2),
    (2, 2), 
    (3, 3), 
    (4, 4),
    (5, 5),
    (6, 1),
    (7, 2),
    (8, 3),
    (9, 4),
    (10, 5);